name: CI
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubunut-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run Build
        run: yarn run build

      - name: Run Tests
        run: yarn test

      - name: Run Coverage
        uses: romeovs/lcov-reporter-action@latest
        with:
          lcov-file: ./coverage/lcov.info
